### ISSUE TITLE
7.6 poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [dawidbar/learning-git-2#1]
- [x] popraw wciecia w pliku `package.json`, zwykle stosuje sie wciecia na 2 lub 4 spacje, u ciebie sa wciecia na 1 spacje
- [x] w pliku `package.json` wszystkie paczki npm'a, ktore akurat tutaj uzywamy powinny byc w `devDependencies`. Brakuje tez kilku zaleznosci przez co kiedy odpalam Twoj projekt, to skrypty mi nie dzialaja. Mozesz to przetestowac u siebie lokalnie usuwajac folder `node_modules` oraz plik `package-lock.json` i odpalajac na swiezo `npm install`, zeby zainstalowac wszystkie zaleznosci projektu, a nastepnie probujac odpalic np `npm run build`
- [x] w tasku `watch:sassprefixer` dodaj spacje po `--`, opoznienie nie jest juz potrzebne i zauwaz, ze skrypty po `--` mozesz zastapic nazwami taskow, ktore juz wczesniej masz zdefiniowane
- [x] task `watch:browsersync` nie dziala. W razie potrzeby zajrzyj do dokumentacji: https://www.browsersync.io/docs/command-line

**Comment by dawidbar** [comment]
Done
